// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ProtoDzh.proto

package com.hw.dzh.data.proto;

public final class ProtoDzh {
  private ProtoDzh() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code com.hw.dzh.data.proto.AccountType}
   */
  public enum AccountType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ACCOUNT_UNKNOWN = 0;</code>
     */
    ACCOUNT_UNKNOWN(0, 0),
    /**
     * <code>ACCOUNT_QQ = 1;</code>
     */
    ACCOUNT_QQ(1, 1),
    /**
     * <code>ACCOUNT_WECHAT = 2;</code>
     */
    ACCOUNT_WECHAT(2, 2),
    /**
     * <code>ACCOUNT_SINAWEIBO = 3;</code>
     */
    ACCOUNT_SINAWEIBO(3, 3),
    ;

    /**
     * <code>ACCOUNT_UNKNOWN = 0;</code>
     */
    public static final int ACCOUNT_UNKNOWN_VALUE = 0;
    /**
     * <code>ACCOUNT_QQ = 1;</code>
     */
    public static final int ACCOUNT_QQ_VALUE = 1;
    /**
     * <code>ACCOUNT_WECHAT = 2;</code>
     */
    public static final int ACCOUNT_WECHAT_VALUE = 2;
    /**
     * <code>ACCOUNT_SINAWEIBO = 3;</code>
     */
    public static final int ACCOUNT_SINAWEIBO_VALUE = 3;


    public final int getNumber() { return value; }

    public static AccountType valueOf(int value) {
      switch (value) {
        case 0: return ACCOUNT_UNKNOWN;
        case 1: return ACCOUNT_QQ;
        case 2: return ACCOUNT_WECHAT;
        case 3: return ACCOUNT_SINAWEIBO;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<AccountType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<AccountType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<AccountType>() {
            public AccountType findValueByNumber(int number) {
              return AccountType.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.hw.dzh.data.proto.ProtoDzh.getDescriptor().getEnumTypes().get(0);
    }

    private static final AccountType[] VALUES = values();

    public static AccountType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private AccountType(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.hw.dzh.data.proto.AccountType)
  }

  public interface ProtoPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.hw.dzh.data.proto.ProtoPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string serverName = 1;</code>
     */
    boolean hasServerName();
    /**
     * <code>required string serverName = 1;</code>
     */
    java.lang.String getServerName();
    /**
     * <code>required string serverName = 1;</code>
     */
    com.google.protobuf.ByteString
        getServerNameBytes();

    /**
     * <code>required string funcName = 2;</code>
     */
    boolean hasFuncName();
    /**
     * <code>required string funcName = 2;</code>
     */
    java.lang.String getFuncName();
    /**
     * <code>required string funcName = 2;</code>
     */
    com.google.protobuf.ByteString
        getFuncNameBytes();

    /**
     * <code>required bytes payload = 3;</code>
     */
    boolean hasPayload();
    /**
     * <code>required bytes payload = 3;</code>
     */
    com.google.protobuf.ByteString getPayload();
  }
  /**
   * Protobuf type {@code com.hw.dzh.data.proto.ProtoPacket}
   */
  public static final class ProtoPacket extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.hw.dzh.data.proto.ProtoPacket)
      ProtoPacketOrBuilder {
    // Use ProtoPacket.newBuilder() to construct.
    private ProtoPacket(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private ProtoPacket(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final ProtoPacket defaultInstance;
    public static ProtoPacket getDefaultInstance() {
      return defaultInstance;
    }

    public ProtoPacket getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private ProtoPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              serverName_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              funcName_ = bs;
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              payload_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hw.dzh.data.proto.ProtoDzh.internal_static_com_hw_dzh_data_proto_ProtoPacket_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hw.dzh.data.proto.ProtoDzh.internal_static_com_hw_dzh_data_proto_ProtoPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hw.dzh.data.proto.ProtoDzh.ProtoPacket.class, com.hw.dzh.data.proto.ProtoDzh.ProtoPacket.Builder.class);
    }

    public static com.google.protobuf.Parser<ProtoPacket> PARSER =
        new com.google.protobuf.AbstractParser<ProtoPacket>() {
      public ProtoPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ProtoPacket(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<ProtoPacket> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int SERVERNAME_FIELD_NUMBER = 1;
    private java.lang.Object serverName_;
    /**
     * <code>required string serverName = 1;</code>
     */
    public boolean hasServerName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string serverName = 1;</code>
     */
    public java.lang.String getServerName() {
      java.lang.Object ref = serverName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          serverName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string serverName = 1;</code>
     */
    public com.google.protobuf.ByteString
        getServerNameBytes() {
      java.lang.Object ref = serverName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        serverName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int FUNCNAME_FIELD_NUMBER = 2;
    private java.lang.Object funcName_;
    /**
     * <code>required string funcName = 2;</code>
     */
    public boolean hasFuncName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string funcName = 2;</code>
     */
    public java.lang.String getFuncName() {
      java.lang.Object ref = funcName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          funcName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string funcName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getFuncNameBytes() {
      java.lang.Object ref = funcName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        funcName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PAYLOAD_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString payload_;
    /**
     * <code>required bytes payload = 3;</code>
     */
    public boolean hasPayload() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required bytes payload = 3;</code>
     */
    public com.google.protobuf.ByteString getPayload() {
      return payload_;
    }

    private void initFields() {
      serverName_ = "";
      funcName_ = "";
      payload_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasServerName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasFuncName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasPayload()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getServerNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getFuncNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, payload_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getServerNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getFuncNameBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, payload_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hw.dzh.data.proto.ProtoDzh.ProtoPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hw.dzh.data.proto.ProtoDzh.ProtoPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hw.dzh.data.proto.ProtoDzh.ProtoPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hw.dzh.data.proto.ProtoDzh.ProtoPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hw.dzh.data.proto.ProtoDzh.ProtoPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hw.dzh.data.proto.ProtoDzh.ProtoPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hw.dzh.data.proto.ProtoDzh.ProtoPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hw.dzh.data.proto.ProtoDzh.ProtoPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hw.dzh.data.proto.ProtoDzh.ProtoPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hw.dzh.data.proto.ProtoDzh.ProtoPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hw.dzh.data.proto.ProtoDzh.ProtoPacket prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.hw.dzh.data.proto.ProtoPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.hw.dzh.data.proto.ProtoPacket)
        com.hw.dzh.data.proto.ProtoDzh.ProtoPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hw.dzh.data.proto.ProtoDzh.internal_static_com_hw_dzh_data_proto_ProtoPacket_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hw.dzh.data.proto.ProtoDzh.internal_static_com_hw_dzh_data_proto_ProtoPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hw.dzh.data.proto.ProtoDzh.ProtoPacket.class, com.hw.dzh.data.proto.ProtoDzh.ProtoPacket.Builder.class);
      }

      // Construct using com.hw.dzh.data.proto.ProtoDzh.ProtoPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        serverName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        funcName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        payload_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hw.dzh.data.proto.ProtoDzh.internal_static_com_hw_dzh_data_proto_ProtoPacket_descriptor;
      }

      public com.hw.dzh.data.proto.ProtoDzh.ProtoPacket getDefaultInstanceForType() {
        return com.hw.dzh.data.proto.ProtoDzh.ProtoPacket.getDefaultInstance();
      }

      public com.hw.dzh.data.proto.ProtoDzh.ProtoPacket build() {
        com.hw.dzh.data.proto.ProtoDzh.ProtoPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hw.dzh.data.proto.ProtoDzh.ProtoPacket buildPartial() {
        com.hw.dzh.data.proto.ProtoDzh.ProtoPacket result = new com.hw.dzh.data.proto.ProtoDzh.ProtoPacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.serverName_ = serverName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.funcName_ = funcName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.payload_ = payload_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hw.dzh.data.proto.ProtoDzh.ProtoPacket) {
          return mergeFrom((com.hw.dzh.data.proto.ProtoDzh.ProtoPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hw.dzh.data.proto.ProtoDzh.ProtoPacket other) {
        if (other == com.hw.dzh.data.proto.ProtoDzh.ProtoPacket.getDefaultInstance()) return this;
        if (other.hasServerName()) {
          bitField0_ |= 0x00000001;
          serverName_ = other.serverName_;
          onChanged();
        }
        if (other.hasFuncName()) {
          bitField0_ |= 0x00000002;
          funcName_ = other.funcName_;
          onChanged();
        }
        if (other.hasPayload()) {
          setPayload(other.getPayload());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasServerName()) {
          
          return false;
        }
        if (!hasFuncName()) {
          
          return false;
        }
        if (!hasPayload()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hw.dzh.data.proto.ProtoDzh.ProtoPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hw.dzh.data.proto.ProtoDzh.ProtoPacket) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object serverName_ = "";
      /**
       * <code>required string serverName = 1;</code>
       */
      public boolean hasServerName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string serverName = 1;</code>
       */
      public java.lang.String getServerName() {
        java.lang.Object ref = serverName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            serverName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string serverName = 1;</code>
       */
      public com.google.protobuf.ByteString
          getServerNameBytes() {
        java.lang.Object ref = serverName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          serverName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string serverName = 1;</code>
       */
      public Builder setServerName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serverName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string serverName = 1;</code>
       */
      public Builder clearServerName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        serverName_ = getDefaultInstance().getServerName();
        onChanged();
        return this;
      }
      /**
       * <code>required string serverName = 1;</code>
       */
      public Builder setServerNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        serverName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object funcName_ = "";
      /**
       * <code>required string funcName = 2;</code>
       */
      public boolean hasFuncName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string funcName = 2;</code>
       */
      public java.lang.String getFuncName() {
        java.lang.Object ref = funcName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            funcName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string funcName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getFuncNameBytes() {
        java.lang.Object ref = funcName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          funcName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string funcName = 2;</code>
       */
      public Builder setFuncName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        funcName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string funcName = 2;</code>
       */
      public Builder clearFuncName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        funcName_ = getDefaultInstance().getFuncName();
        onChanged();
        return this;
      }
      /**
       * <code>required string funcName = 2;</code>
       */
      public Builder setFuncNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        funcName_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString payload_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes payload = 3;</code>
       */
      public boolean hasPayload() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required bytes payload = 3;</code>
       */
      public com.google.protobuf.ByteString getPayload() {
        return payload_;
      }
      /**
       * <code>required bytes payload = 3;</code>
       */
      public Builder setPayload(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        payload_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes payload = 3;</code>
       */
      public Builder clearPayload() {
        bitField0_ = (bitField0_ & ~0x00000004);
        payload_ = getDefaultInstance().getPayload();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.hw.dzh.data.proto.ProtoPacket)
    }

    static {
      defaultInstance = new ProtoPacket(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.hw.dzh.data.proto.ProtoPacket)
  }

  public interface UserInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.hw.dzh.data.proto.UserInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required .com.hw.dzh.data.proto.AccountType eAccountType = 1 [default = ACCOUNT_UNKNOWN];</code>
     */
    boolean hasEAccountType();
    /**
     * <code>required .com.hw.dzh.data.proto.AccountType eAccountType = 1 [default = ACCOUNT_UNKNOWN];</code>
     */
    com.hw.dzh.data.proto.ProtoDzh.AccountType getEAccountType();

    /**
     * <code>required string sUserId = 2;</code>
     */
    boolean hasSUserId();
    /**
     * <code>required string sUserId = 2;</code>
     */
    java.lang.String getSUserId();
    /**
     * <code>required string sUserId = 2;</code>
     */
    com.google.protobuf.ByteString
        getSUserIdBytes();

    /**
     * <code>optional string sNickname = 3;</code>
     *
     * <pre>
     * 昵称
     * </pre>
     */
    boolean hasSNickname();
    /**
     * <code>optional string sNickname = 3;</code>
     *
     * <pre>
     * 昵称
     * </pre>
     */
    java.lang.String getSNickname();
    /**
     * <code>optional string sNickname = 3;</code>
     *
     * <pre>
     * 昵称
     * </pre>
     */
    com.google.protobuf.ByteString
        getSNicknameBytes();

    /**
     * <code>optional string sFaceIcon = 4;</code>
     *
     * <pre>
     * 头像
     * </pre>
     */
    boolean hasSFaceIcon();
    /**
     * <code>optional string sFaceIcon = 4;</code>
     *
     * <pre>
     * 头像
     * </pre>
     */
    java.lang.String getSFaceIcon();
    /**
     * <code>optional string sFaceIcon = 4;</code>
     *
     * <pre>
     * 头像
     * </pre>
     */
    com.google.protobuf.ByteString
        getSFaceIconBytes();
  }
  /**
   * Protobuf type {@code com.hw.dzh.data.proto.UserInfo}
   */
  public static final class UserInfo extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:com.hw.dzh.data.proto.UserInfo)
      UserInfoOrBuilder {
    // Use UserInfo.newBuilder() to construct.
    private UserInfo(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private UserInfo(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final UserInfo defaultInstance;
    public static UserInfo getDefaultInstance() {
      return defaultInstance;
    }

    public UserInfo getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private UserInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              com.hw.dzh.data.proto.ProtoDzh.AccountType value = com.hw.dzh.data.proto.ProtoDzh.AccountType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                eAccountType_ = value;
              }
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              sUserId_ = bs;
              break;
            }
            case 26: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              sNickname_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000008;
              sFaceIcon_ = bs;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.hw.dzh.data.proto.ProtoDzh.internal_static_com_hw_dzh_data_proto_UserInfo_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.hw.dzh.data.proto.ProtoDzh.internal_static_com_hw_dzh_data_proto_UserInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.hw.dzh.data.proto.ProtoDzh.UserInfo.class, com.hw.dzh.data.proto.ProtoDzh.UserInfo.Builder.class);
    }

    public static com.google.protobuf.Parser<UserInfo> PARSER =
        new com.google.protobuf.AbstractParser<UserInfo>() {
      public UserInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new UserInfo(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<UserInfo> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int EACCOUNTTYPE_FIELD_NUMBER = 1;
    private com.hw.dzh.data.proto.ProtoDzh.AccountType eAccountType_;
    /**
     * <code>required .com.hw.dzh.data.proto.AccountType eAccountType = 1 [default = ACCOUNT_UNKNOWN];</code>
     */
    public boolean hasEAccountType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required .com.hw.dzh.data.proto.AccountType eAccountType = 1 [default = ACCOUNT_UNKNOWN];</code>
     */
    public com.hw.dzh.data.proto.ProtoDzh.AccountType getEAccountType() {
      return eAccountType_;
    }

    public static final int SUSERID_FIELD_NUMBER = 2;
    private java.lang.Object sUserId_;
    /**
     * <code>required string sUserId = 2;</code>
     */
    public boolean hasSUserId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required string sUserId = 2;</code>
     */
    public java.lang.String getSUserId() {
      java.lang.Object ref = sUserId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sUserId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string sUserId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSUserIdBytes() {
      java.lang.Object ref = sUserId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sUserId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SNICKNAME_FIELD_NUMBER = 3;
    private java.lang.Object sNickname_;
    /**
     * <code>optional string sNickname = 3;</code>
     *
     * <pre>
     * 昵称
     * </pre>
     */
    public boolean hasSNickname() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string sNickname = 3;</code>
     *
     * <pre>
     * 昵称
     * </pre>
     */
    public java.lang.String getSNickname() {
      java.lang.Object ref = sNickname_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sNickname_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sNickname = 3;</code>
     *
     * <pre>
     * 昵称
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSNicknameBytes() {
      java.lang.Object ref = sNickname_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sNickname_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SFACEICON_FIELD_NUMBER = 4;
    private java.lang.Object sFaceIcon_;
    /**
     * <code>optional string sFaceIcon = 4;</code>
     *
     * <pre>
     * 头像
     * </pre>
     */
    public boolean hasSFaceIcon() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string sFaceIcon = 4;</code>
     *
     * <pre>
     * 头像
     * </pre>
     */
    public java.lang.String getSFaceIcon() {
      java.lang.Object ref = sFaceIcon_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sFaceIcon_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string sFaceIcon = 4;</code>
     *
     * <pre>
     * 头像
     * </pre>
     */
    public com.google.protobuf.ByteString
        getSFaceIconBytes() {
      java.lang.Object ref = sFaceIcon_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sFaceIcon_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      eAccountType_ = com.hw.dzh.data.proto.ProtoDzh.AccountType.ACCOUNT_UNKNOWN;
      sUserId_ = "";
      sNickname_ = "";
      sFaceIcon_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasEAccountType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSUserId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, eAccountType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, getSUserIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getSNicknameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getSFaceIconBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, eAccountType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, getSUserIdBytes());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getSNicknameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getSFaceIconBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.hw.dzh.data.proto.ProtoDzh.UserInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hw.dzh.data.proto.ProtoDzh.UserInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hw.dzh.data.proto.ProtoDzh.UserInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.hw.dzh.data.proto.ProtoDzh.UserInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.hw.dzh.data.proto.ProtoDzh.UserInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hw.dzh.data.proto.ProtoDzh.UserInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.hw.dzh.data.proto.ProtoDzh.UserInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.hw.dzh.data.proto.ProtoDzh.UserInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.hw.dzh.data.proto.ProtoDzh.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.hw.dzh.data.proto.ProtoDzh.UserInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.hw.dzh.data.proto.ProtoDzh.UserInfo prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.hw.dzh.data.proto.UserInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.hw.dzh.data.proto.UserInfo)
        com.hw.dzh.data.proto.ProtoDzh.UserInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.hw.dzh.data.proto.ProtoDzh.internal_static_com_hw_dzh_data_proto_UserInfo_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.hw.dzh.data.proto.ProtoDzh.internal_static_com_hw_dzh_data_proto_UserInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.hw.dzh.data.proto.ProtoDzh.UserInfo.class, com.hw.dzh.data.proto.ProtoDzh.UserInfo.Builder.class);
      }

      // Construct using com.hw.dzh.data.proto.ProtoDzh.UserInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        eAccountType_ = com.hw.dzh.data.proto.ProtoDzh.AccountType.ACCOUNT_UNKNOWN;
        bitField0_ = (bitField0_ & ~0x00000001);
        sUserId_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        sNickname_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        sFaceIcon_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.hw.dzh.data.proto.ProtoDzh.internal_static_com_hw_dzh_data_proto_UserInfo_descriptor;
      }

      public com.hw.dzh.data.proto.ProtoDzh.UserInfo getDefaultInstanceForType() {
        return com.hw.dzh.data.proto.ProtoDzh.UserInfo.getDefaultInstance();
      }

      public com.hw.dzh.data.proto.ProtoDzh.UserInfo build() {
        com.hw.dzh.data.proto.ProtoDzh.UserInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.hw.dzh.data.proto.ProtoDzh.UserInfo buildPartial() {
        com.hw.dzh.data.proto.ProtoDzh.UserInfo result = new com.hw.dzh.data.proto.ProtoDzh.UserInfo(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.eAccountType_ = eAccountType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sUserId_ = sUserId_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.sNickname_ = sNickname_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.sFaceIcon_ = sFaceIcon_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.hw.dzh.data.proto.ProtoDzh.UserInfo) {
          return mergeFrom((com.hw.dzh.data.proto.ProtoDzh.UserInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.hw.dzh.data.proto.ProtoDzh.UserInfo other) {
        if (other == com.hw.dzh.data.proto.ProtoDzh.UserInfo.getDefaultInstance()) return this;
        if (other.hasEAccountType()) {
          setEAccountType(other.getEAccountType());
        }
        if (other.hasSUserId()) {
          bitField0_ |= 0x00000002;
          sUserId_ = other.sUserId_;
          onChanged();
        }
        if (other.hasSNickname()) {
          bitField0_ |= 0x00000004;
          sNickname_ = other.sNickname_;
          onChanged();
        }
        if (other.hasSFaceIcon()) {
          bitField0_ |= 0x00000008;
          sFaceIcon_ = other.sFaceIcon_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasEAccountType()) {
          
          return false;
        }
        if (!hasSUserId()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.hw.dzh.data.proto.ProtoDzh.UserInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.hw.dzh.data.proto.ProtoDzh.UserInfo) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.hw.dzh.data.proto.ProtoDzh.AccountType eAccountType_ = com.hw.dzh.data.proto.ProtoDzh.AccountType.ACCOUNT_UNKNOWN;
      /**
       * <code>required .com.hw.dzh.data.proto.AccountType eAccountType = 1 [default = ACCOUNT_UNKNOWN];</code>
       */
      public boolean hasEAccountType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required .com.hw.dzh.data.proto.AccountType eAccountType = 1 [default = ACCOUNT_UNKNOWN];</code>
       */
      public com.hw.dzh.data.proto.ProtoDzh.AccountType getEAccountType() {
        return eAccountType_;
      }
      /**
       * <code>required .com.hw.dzh.data.proto.AccountType eAccountType = 1 [default = ACCOUNT_UNKNOWN];</code>
       */
      public Builder setEAccountType(com.hw.dzh.data.proto.ProtoDzh.AccountType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        eAccountType_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required .com.hw.dzh.data.proto.AccountType eAccountType = 1 [default = ACCOUNT_UNKNOWN];</code>
       */
      public Builder clearEAccountType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        eAccountType_ = com.hw.dzh.data.proto.ProtoDzh.AccountType.ACCOUNT_UNKNOWN;
        onChanged();
        return this;
      }

      private java.lang.Object sUserId_ = "";
      /**
       * <code>required string sUserId = 2;</code>
       */
      public boolean hasSUserId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required string sUserId = 2;</code>
       */
      public java.lang.String getSUserId() {
        java.lang.Object ref = sUserId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sUserId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string sUserId = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSUserIdBytes() {
        java.lang.Object ref = sUserId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sUserId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string sUserId = 2;</code>
       */
      public Builder setSUserId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sUserId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string sUserId = 2;</code>
       */
      public Builder clearSUserId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sUserId_ = getDefaultInstance().getSUserId();
        onChanged();
        return this;
      }
      /**
       * <code>required string sUserId = 2;</code>
       */
      public Builder setSUserIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sUserId_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sNickname_ = "";
      /**
       * <code>optional string sNickname = 3;</code>
       *
       * <pre>
       * 昵称
       * </pre>
       */
      public boolean hasSNickname() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string sNickname = 3;</code>
       *
       * <pre>
       * 昵称
       * </pre>
       */
      public java.lang.String getSNickname() {
        java.lang.Object ref = sNickname_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sNickname_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sNickname = 3;</code>
       *
       * <pre>
       * 昵称
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSNicknameBytes() {
        java.lang.Object ref = sNickname_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sNickname_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sNickname = 3;</code>
       *
       * <pre>
       * 昵称
       * </pre>
       */
      public Builder setSNickname(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        sNickname_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sNickname = 3;</code>
       *
       * <pre>
       * 昵称
       * </pre>
       */
      public Builder clearSNickname() {
        bitField0_ = (bitField0_ & ~0x00000004);
        sNickname_ = getDefaultInstance().getSNickname();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sNickname = 3;</code>
       *
       * <pre>
       * 昵称
       * </pre>
       */
      public Builder setSNicknameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        sNickname_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sFaceIcon_ = "";
      /**
       * <code>optional string sFaceIcon = 4;</code>
       *
       * <pre>
       * 头像
       * </pre>
       */
      public boolean hasSFaceIcon() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string sFaceIcon = 4;</code>
       *
       * <pre>
       * 头像
       * </pre>
       */
      public java.lang.String getSFaceIcon() {
        java.lang.Object ref = sFaceIcon_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sFaceIcon_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string sFaceIcon = 4;</code>
       *
       * <pre>
       * 头像
       * </pre>
       */
      public com.google.protobuf.ByteString
          getSFaceIconBytes() {
        java.lang.Object ref = sFaceIcon_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sFaceIcon_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string sFaceIcon = 4;</code>
       *
       * <pre>
       * 头像
       * </pre>
       */
      public Builder setSFaceIcon(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        sFaceIcon_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string sFaceIcon = 4;</code>
       *
       * <pre>
       * 头像
       * </pre>
       */
      public Builder clearSFaceIcon() {
        bitField0_ = (bitField0_ & ~0x00000008);
        sFaceIcon_ = getDefaultInstance().getSFaceIcon();
        onChanged();
        return this;
      }
      /**
       * <code>optional string sFaceIcon = 4;</code>
       *
       * <pre>
       * 头像
       * </pre>
       */
      public Builder setSFaceIconBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        sFaceIcon_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:com.hw.dzh.data.proto.UserInfo)
    }

    static {
      defaultInstance = new UserInfo(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:com.hw.dzh.data.proto.UserInfo)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hw_dzh_data_proto_ProtoPacket_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hw_dzh_data_proto_ProtoPacket_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_hw_dzh_data_proto_UserInfo_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_hw_dzh_data_proto_UserInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016ProtoDzh.proto\022\025com.hw.dzh.data.proto\"" +
      "D\n\013ProtoPacket\022\022\n\nserverName\030\001 \002(\t\022\020\n\010fu" +
      "ncName\030\002 \002(\t\022\017\n\007payload\030\003 \002(\014\"\214\001\n\010UserIn" +
      "fo\022I\n\014eAccountType\030\001 \002(\0162\".com.hw.dzh.da" +
      "ta.proto.AccountType:\017ACCOUNT_UNKNOWN\022\017\n" +
      "\007sUserId\030\002 \002(\t\022\021\n\tsNickname\030\003 \001(\t\022\021\n\tsFa" +
      "ceIcon\030\004 \001(\t*]\n\013AccountType\022\023\n\017ACCOUNT_U" +
      "NKNOWN\020\000\022\016\n\nACCOUNT_QQ\020\001\022\022\n\016ACCOUNT_WECH" +
      "AT\020\002\022\025\n\021ACCOUNT_SINAWEIBO\020\003B\nB\010ProtoDzh"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_hw_dzh_data_proto_ProtoPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_hw_dzh_data_proto_ProtoPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_hw_dzh_data_proto_ProtoPacket_descriptor,
        new java.lang.String[] { "ServerName", "FuncName", "Payload", });
    internal_static_com_hw_dzh_data_proto_UserInfo_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_com_hw_dzh_data_proto_UserInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_com_hw_dzh_data_proto_UserInfo_descriptor,
        new java.lang.String[] { "EAccountType", "SUserId", "SNickname", "SFaceIcon", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
